//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wpf_Traffic_violation.MagrationDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activity
    {
        public int Activity_id { get; set; }
        public System.DateTime Activity_date { get; set; }
        public int User_id { get; set; }
        public int Form_id { get; set; }
        public int Activity_operation_num { get; set; }
        public int Activity_record_num { get; set; }
    
        public virtual Form Form { get; set; }
        public virtual User User { get; set; }
    }
}
