//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wpf_Traffic_violation.MagrationDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bond_Exchange_detail
    {
        public int Bond_Exchange_detail_id { get; set; }
        public int Bond_Exchange_id { get; set; }
        public string Bond_Exchange_detail_statement { get; set; }
        public int Bond_Exchange_detail_amount { get; set; }
    
        public virtual Bond_Exchange Bond_Exchange { get; set; }
    }
}
