//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wpf_Traffic_violation.MagrationDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bond_Exchange
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bond_Exchange()
        {
            this.Bond_Exchange_detail = new HashSet<Bond_Exchange_detail>();
        }
    
        public int Bond_Exchange_id { get; set; }
        public System.DateTime Bond_Exchange_date { get; set; }
        public int Account_id { get; set; }
        public string Bond_Exchange_statement { get; set; }
        public int Bond_Exchange_amount { get; set; }
        public int Bond_Exchange_status { get; set; }
        public Nullable<System.DateTime> Post_date { get; set; }
    
        public virtual Account Account { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bond_Exchange_detail> Bond_Exchange_detail { get; set; }
    }
}
