//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wpf_Traffic_violation.MagrationDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Citizen
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Citizen()
        {
            this.Driving_license = new HashSet<Driving_license>();
            this.Interceptions = new HashSet<Interception>();
            this.Vehicle_card = new HashSet<Vehicle_card>();
        }
    
        public int Citizen_id { get; set; }
        public string Citizen_name { get; set; }
        public string Citizen_address { get; set; }
        public System.DateTime Citizen_date_pirth { get; set; }
        public string Citizen_religion { get; set; }
        public string Citizen_blood_type { get; set; }
        public int Citizen_social_status { get; set; }
        public int User_id { get; set; }
    
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Driving_license> Driving_license { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Interception> Interceptions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vehicle_card> Vehicle_card { get; set; }
    }
}
