//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wpf_Traffic_violation.MagrationDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Communication
    {
        public int Communication_id { get; set; }
        public string Communication_name { get; set; }
        public System.DateTime Communication_date { get; set; }
        public int User_id { get; set; }
        public int Plate_id { get; set; }
        public byte[] Communication_photo1 { get; set; }
        public byte[] Communication_photo2 { get; set; }
        public string Communication_notice { get; set; }
        public Nullable<int> Communication_status { get; set; }
    
        public virtual Plate Plate { get; set; }
        public virtual User User { get; set; }
    }
}
