//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wpf_Traffic_violation.MagrationDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public int Company_id { get; set; }
        public string Company_name { get; set; }
        public string Company_ring { get; set; }
        public byte[] Company_logo { get; set; }
        public int Company_phon { get; set; }
        public string Company_address { get; set; }
        public string Company_e_mail { get; set; }
        public int Currancy_id { get; set; }
        public int Status { get; set; }
    
        public virtual Currency Currency { get; set; }
    }
}
