//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wpf_Traffic_violation.MagrationDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Driving_license
    {
        public int Driving_license_id { get; set; }
        public System.DateTime Release_date { get; set; }
        public int Citizen_id { get; set; }
        public int Class_license_id { get; set; }
        public System.DateTime Date_frist_license { get; set; }
        public string Driving_license_notice { get; set; }
        public string status { get; set; }
    
        public virtual Citizen Citizen { get; set; }
        public virtual Class_licence Class_licence { get; set; }
    }
}
