//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wpf_Traffic_violation.MagrationDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entry_detail
    {
        public int Entry_id { get; set; }
        public int Account_id { get; set; }
        public int Debit { get; set; }
        public int Credit { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Entry Entry { get; set; }
    }
}
