//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wpf_Traffic_violation.MagrationDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Interception
    {
        public int Interception_id { get; set; }
        public System.DateTime Interception_date { get; set; }
        public string Reason_Interception { get; set; }
        public int Violation_id { get; set; }
        public int Identity_id { get; set; }
        public Nullable<int> Status { get; set; }
    
        public virtual Citizen Citizen { get; set; }
    }
}
