//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wpf_Traffic_violation.MagrationDB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TrafficViolationEntitiesUat : DbContext
    {
        public TrafficViolationEntitiesUat()
            : base("name=TrafficViolationEntitiesUat")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<Activity> Activities { get; set; }
        public virtual DbSet<Bank_account> Bank_account { get; set; }
        public virtual DbSet<Bond_Exchange> Bond_Exchange { get; set; }
        public virtual DbSet<Bond_Exchange_detail> Bond_Exchange_detail { get; set; }
        public virtual DbSet<Citizen> Citizens { get; set; }
        public virtual DbSet<Class_licence> Class_licence { get; set; }
        public virtual DbSet<Communication> Communications { get; set; }
        public virtual DbSet<Company> Companies { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<Currency> Currencies { get; set; }
        public virtual DbSet<Directorate> Directorates { get; set; }
        public virtual DbSet<Driving_license> Driving_license { get; set; }
        public virtual DbSet<Entry> Entries { get; set; }
        public virtual DbSet<Form> Forms { get; set; }
        public virtual DbSet<Group> Groups { get; set; }
        public virtual DbSet<Interception> Interceptions { get; set; }
        public virtual DbSet<Menu> Menus { get; set; }
        public virtual DbSet<Plate> Plates { get; set; }
        public virtual DbSet<Plate_type> Plate_type { get; set; }
        public virtual DbSet<PlateDetaile> PlateDetailes { get; set; }
        public virtual DbSet<Province> Provinces { get; set; }
        public virtual DbSet<Reason_interception> Reason_interception { get; set; }
        public virtual DbSet<Receipt> Receipts { get; set; }
        public virtual DbSet<Receipt_detail> Receipt_detail { get; set; }
        public virtual DbSet<Street> Streets { get; set; }
        public virtual DbSet<Supply> Supplies { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Traffic_man> Traffic_man { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Vehicle> Vehicles { get; set; }
        public virtual DbSet<Vehicle_card> Vehicle_card { get; set; }
        public virtual DbSet<Violation> Violations { get; set; }
        public virtual DbSet<Violation_type> Violation_type { get; set; }
        public virtual DbSet<Entry_detail> Entry_detail { get; set; }
        public virtual DbSet<Plate_global> Plate_global { get; set; }
        public virtual DbSet<Plate_local> Plate_local { get; set; }
        public virtual DbSet<Privilege_group> Privilege_group { get; set; }
        public virtual DbSet<Privilege_user> Privilege_user { get; set; }
    }
}
