//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wpf_Traffic_violation.MagrationDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlateDetaile
    {
        public int ID { get; set; }
        public System.DateTime Release_date { get; set; }
        public string Plate_num { get; set; }
        public int Province_id { get; set; }
        public int plate_type { get; set; }
        public string Noties { get; set; }
        public Nullable<int> Status { get; set; }
        public string PlateName { get; set; }
    
        public virtual Province Province { get; set; }
    }
}
