//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wpf_Traffic_violation.MagrationDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plate_local
    {
        public int Plate_type_id { get; set; }
        public int ID { get; set; }
        public int Province_id { get; set; }
    
        public virtual Plate Plate { get; set; }
        public virtual Plate_type Plate_type { get; set; }
        public virtual Province Province { get; set; }
    }
}
