//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wpf_Traffic_violation.MagrationDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Privilege_group
    {
        public int Group_id { get; set; }
        public int Form_id { get; set; }
        public bool Privilege_add { get; set; }
        public bool Privilege_delete { get; set; }
        public bool Privilege_update { get; set; }
        public bool Privilege_select { get; set; }
        public bool Privilege_form { get; set; }
    
        public virtual Form Form { get; set; }
        public virtual Group Group { get; set; }
    }
}
