//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wpf_Traffic_violation.MagrationDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Receipt
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Receipt()
        {
            this.Receipt_detail = new HashSet<Receipt_detail>();
        }
    
        public int Receipt_id { get; set; }
        public System.DateTime Receipt_date { get; set; }
        public int Account_id { get; set; }
        public string Receipt_statement { get; set; }
        public int Receipt_amount { get; set; }
        public Nullable<bool> Receipt_status { get; set; }
        public Nullable<System.DateTime> Post_date { get; set; }
    
        public virtual Account Account { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Receipt_detail> Receipt_detail { get; set; }
    }
}
