//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wpf_Traffic_violation.MagrationDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Receipt_detail
    {
        public int Receipt_detail_id { get; set; }
        public int Receipt_id { get; set; }
        public string Receipt_detail_statement { get; set; }
        public int Violation_id { get; set; }
        public int Receipt_detail_amount { get; set; }
        public Nullable<int> Receipt_amountwithdiscont { get; set; }
        public string NameOfPaid { get; set; }
        public string ResonOfPaid { get; set; }
    
        public virtual Receipt Receipt { get; set; }
        public virtual Violation Violation { get; set; }
    }
}
