//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wpf_Traffic_violation.MagrationDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Street
    {
        public int Street_id { get; set; }
        public string Street_name { get; set; }
        public int Directerate_id { get; set; }
    
        public virtual Directorate Directorate { get; set; }
    }
}
