//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wpf_Traffic_violation.MagrationDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supply
    {
        public int Supply_id { get; set; }
        public System.DateTime Supply_date { get; set; }
        public int Supply_amount { get; set; }
        public int Account_id { get; set; }
        public int Violation_id { get; set; }
        public int Bank_id { get; set; }
        public int Reference_num { get; set; }
        public Nullable<int> Status { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Bank_account Bank_account { get; set; }
    }
}
