//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wpf_Traffic_violation.MagrationDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicle_card
    {
        public int Vehicle_card_id { get; set; }
        public System.DateTime Release_date { get; set; }
        public int Release_plase { get; set; }
        public int Citizen_id { get; set; }
        public int Vohicle_id { get; set; }
        public string Noties { get; set; }
        public Nullable<int> Status { get; set; }
    
        public virtual Citizen Citizen { get; set; }
        public virtual Vehicle Vehicle { get; set; }
    }
}
