//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wpf_Traffic_violation.MagrationDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vehicle()
        {
            this.Vehicle_card = new HashSet<Vehicle_card>();
        }
    
        public int Potty_id { get; set; }
        public int Vehicle_engine_num { get; set; }
        public string Vehicle_color { get; set; }
        public string Vehicle_shape { get; set; }
        public string Vehicle_model { get; set; }
        public int Vehicle_customs_num { get; set; }
        public System.DateTime Release_date { get; set; }
        public string company_manu_name { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> Release_palc { get; set; }
    
        public virtual Province Province { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vehicle_card> Vehicle_card { get; set; }
    }
}
