//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wpf_Traffic_violation.MagrationDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Violation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Violation()
        {
            this.Receipt_detail = new HashSet<Receipt_detail>();
        }
    
        public int Violation_id { get; set; }
        public System.DateTime Violation_date { get; set; }
        public byte[] Violation_photo1 { get; set; }
        public byte[] Violation_photo2 { get; set; }
        public int Plate_id { get; set; }
        public int Street_id { get; set; }
        public int Teaffic_man_id { get; set; }
        public int Violation_type_id { get; set; }
        public string Notise { get; set; }
        public Nullable<int> Violation_penalty { get; set; }
        public Nullable<int> Payment_status { get; set; }
        public string CreatedOn { get; set; }
        public Nullable<int> Createdby { get; set; }
        public string UpdateOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<int> VounchrNum { get; set; }
        public Nullable<int> Provinceid { get; set; }
        public string vehicle_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Receipt_detail> Receipt_detail { get; set; }
        public virtual Traffic_man Traffic_man { get; set; }
        public virtual Violation_type Violation_type { get; set; }
    }
}
