namespace Wpf_Traffic_violation.Core.DataBase.Storedprocedures
{
    public class OpreationSql
    {
        public string SP_Director_Opreation = "CREATE PROCEDURE [dbo].[SP_Director_Opreation]\r\n\t@Operation nvarchar(50),\r\n\t@Province_name nvarchar(50),\r\n\t@Directorate_name nvarchar(20),\r\n\t@Directorate_id int\r\nas\r\nBEGIN\r\nDECLARE @INSERTEDPROVINCEID TABLE (\r\n    PROVINCE_ID INT\r\n);\r\n\tSET NOCOUNT ON;\r\n\t\r\n\tIF(@OPERATION='INSERT')\r\n\tBEGIN\r\n\t\r\n\t SET  IDENTITY_INSERT [PROVINCE]   ON\r\n\r\n\t   INSERT INTO [DBO].[PROVINCE] (PROVINCE_ID,[PROVINCE_NAME])  \r\n\t         OUTPUT INSERTED.PROVINCE_ID INTO @INSERTEDPROVINCEID\r\n\t         VALUES (@DIRECTORATE_ID, @PROVINCE_NAME);\r\n\t   INSERT INTO [DBO].[DIRECTORATE]\r\n           ([DIRECTORATE_NAME]\r\n           ,[PROVINCE_ID])\r\n     VALUES\r\n           (@DIRECTORATE_NAME,\r\n           (SELECT * FROM @INSERTEDPROVINCEID))\r\n  SET  IDENTITY_INSERT [PROVINCE]   OFF\r\n\t  END\r\n\r\n ELSE IF(@OPERATION='DELETE')\r\n  BEGIN\r\n  DECLARE @PROVIDID INT=(SELECT PROV.PROVINCE_ID FROM PROVINCE PROV WITH(NOLOCK) \r\n                  INNER JOIN DIRECTORATE DIRECT WITH(NOLOCK) ON DIRECT.PROVINCE_ID=PROV.PROVINCE_ID\r\n\t\t\t\t        WHERE DIRECT.DIRECTORATE_ID=@DIRECTORATE_ID )\r\n\r\n  DELETE FROM DIRECTORATE WHERE DIRECTORATE_ID=@DIRECTORATE_ID\r\n  DELETE FROM PROVINCE WHERE PROVINCE_ID=@PROVIDID\r\n  END\r\nEND\r\nGO";
        public string Sp_PlateTypeOperation = "CREATE PROCEDURE [dbo].[Sp_PlateTypeOperation] @Plate_type_id int,\r\n @Plate_type_name nvarchar(15),\r\n  @Operation nvarchar(50)\r\n AS BEGIN  \r\n  SET NOCOUNT ON; \r\n  if(@Operation='Insert') \r\n   begin \r\n   SET IDENTITY_INSERT Plate_type ON\r\n    insert into Plate_type (Plate_type_id,   \r\n Plate_type_name, \r\n\t\t\t\t\t   Status)\r\n\t\t\t\t\t values(@Plate_type_id,@Plate_type_name,1)  \r\n\tSET IDENTITY_INSERT Plate_type off\r\n\t\t\t\t\t\tend \r\nEND ";
        public string OperationViolationtype = "CREATE PROCEDURE [dbo].[opViolationType]\r\n\t@Violation_type_id int ,\r\n\t@Violation_type_name int,\r\n\t@Minimum_price int,\r\n\t@Maximum_price int,\r\n\t@Penalty int ,\r\n\t@Interception_status bit =1,\r\n\t@Operation nvarchar (50)\r\n\r\nAS\r\nBEGIN\r\n\t\r\n\tSET NOCOUNT ON;\r\n\tif(@Operation ='Insert')\r\n\tbegin\r\n\tINSERT INTO [dbo].[Violation_type]\r\n           ([Violation_type_name]\r\n           ,[Minimum_price]\r\n           ,[Maximum_price]\r\n           ,[Penalty]\r\n           ,[Interception_status])\r\n     VALUES\r\n           (@Violation_type_name\r\n           ,@Minimum_price\r\n           ,@Maximum_price\r\n           ,@Penalty\r\n           ,@Interception_status)\r\n\t end\r\nEND";
        public string opStreets = "CREATE PROCEDURE [dbo].[opStreets]\r\n@Street_id int,\r\n@Street_name nvarchar(25),\r\n@Directerate_id int,\r\n@Operation nvarchar(50)\r\nAS\r\nBEGIN\r\n\tif(@Operation='Insert')\r\n\tbegin\r\n\tINSERT INTO [dbo].[Street]\r\n           ([Street_name]\r\n           ,[Directerate_id])\r\n     VALUES\r\n           (@Street_name\r\n           ,@Directerate_id) \r\n\tend\r\nEND";
        public string opReviewViolation = "\r\nCREATE PROCEDURE opReviewViolation\r\n\r\n@vehicleId int,\r\n@violationType nvarchar(10),\r\n@violationprov nvarchar(10)\r\nAS\r\nBEGIN\r\nINSERT INTO [dbo].[ReviewViolation]\r\n           (\r\n           [vehicleId]\r\n           ,[violationType]\r\n           ,[violationprov]\r\n           ,[DateReview])\r\n     VALUES\r\n           ( @vehicleId\r\n           ,@violationType\r\n           ,@violationprov\r\n           ,GETDATE())\r\nEND\r\nGO\r\n";
    }
}
