namespace Wpf_Traffic_violation.Services.DataBase.Storedprocedures
{
    public class SP_Query
    {


        public SP_Query() { }

        public string SP_GetViolationTye = "Create PROCEDURE [dbo].[GetViolationTypes]\r\n\r\nAS\r\nBEGIN\r\n\t\r\nSELECT [Violation_type_id]\r\n      ,[Violation_type_name]\r\n      ,[Minimum_price]\r\n      ,[Maximum_price]\r\n      ,[Penalty]\r\n      ,[Interception_status]\r\n  FROM [dbo].[Violation_type]\r\nEND";
        public string SP_GetDirectorate = "CREATE PROCEDURE [dbo].[GetDirectorate]  \r\nAS\r\nBEGIN\r\n\tSET NOCOUNT ON;\r\n\r\n\tSELECT [Directorate_id],[Directorate_name],[Province_id] FROM [dbo].[Directorate]\r\nEND";
        public string SP_getprovincById = "CREATE PROCEDURE  [dbo].[GetPtovinceById]   \r\n@Province_id int \r\nAS\r\nBEGIN\r\n\tSET NOCOUNT ON;\r\n\r\n\tSELECT [Province_id],[Province_name] FROM [dbo].[Province] where Province_id= @Province_id\r\nEND";
        public string SP_getprovincNameById = "CREATE PROCEDURE  [dbo].[GetPtovinceById]   \r\n@Province_id int \r\nAS\r\nBEGIN\r\n\tSET NOCOUNT ON;\r\n\r\n\tSELECT [Province_name] FROM [dbo].[Province] where Province_id= @Province_id\r\nEND";
        public string GetplateType = "CREATE PROCEDURE [dbo].[GetplateType]\r\n\r\n\t\r\nAS\r\nBEGIN\r\n\tSET NOCOUNT ON;\r\n\t\r\nSELECT [Plate_type_id]\r\n      ,[Plate_type_name]\r\n      ,[Status]\r\n  FROM [dbo].[Plate_type]\r\nEND";
        public string Get_Province = "CREATE PROCEDURE [dbo].[Get_Province]\r\n\t\r\nAS\r\nBEGIN\r\n \r\n\tSET NOCOUNT ON;\r\n\tSELECT [Province_id]\r\n      ,[Province_name]\r\n  FROM [dbo].[Province]\r\nEND";
        public string getMaxId = "CREATE PROCEDURE [dbo].[getMaxId] \r\n   @coulmName NVARCHAR(100),\r\n    @TableName NVARCHAR(100)\r\nAS\r\nBEGIN\r\n    DECLARE @sqlQuery NVARCHAR(1000)\r\n    SET @sqlQuery = '\r\nSELECT top 1\r\n    ROW_NUMBER() OVER (ORDER BY'+  QUOTENAME(@coulmName)+' DESC) AS LastRowNumber\r\nFROM' +\r\n    QUOTENAME(@TableName) +'order by 1desc '\r\n    EXEC sp_executesql @sqlQuery\r\nEND";
        public string GetplateTypeById = "CREATE PROCEDURE [dbo].[GetplateTypeById]\r\n@Plate_type_id int\r\nAS\r\nBEGIN\r\n\r\n\tSET NOCOUNT ON;\r\n\r\n    \r\n\tSELECT * from Plate_type where Plate_type_id=@Plate_type_id\r\nEND\r\n\r\n";
        public string GetSteetCollection = "Create  PROCEDURE [dbo].[GetStreets]\r\n\t\r\nAS\r\nBEGIN\r\n\tSELECT [Street_id]\r\n      ,[Street_name]\r\n      ,[Directerate_id]\r\n  FROM [dbo].[Street]\r\nEND";
        public string GetNamerow = "CREATE PROCEDURE [dbo].[GetNamerow]\r\n\t-- Add the parameters for the stored procedure here\r\n\t@Operation nvarchar(25),\r\n\t@Id int \r\nAS\r\nBEGIN\r\nDeclare @Result nvarchar (50);\r\n\t\r\n\tSET NOCOUNT ON;\r\n\t\r\n\tif(@Operation='getPlateTypenames')\r\n\tbegin \r\n\tselect Plate_type_name from Plate_type with (nolock) where Plate_type_id=@Id\r\n\tend\r\n\telse if(@Operation='GetViolationtype_name')\r\n\tbegin \r\n\tselect Violation_type_name from Violation_type with (nolock) where Violation_type_id=@Id\r\n\tend\r\n\telse if(@Operation='GetTrafficMan_name')\r\n\tbegin \r\n\tselect Traffic_man_name from Traffic_man with (nolock) where Traffic_man_id=@Id\r\n\tend\r\n\telse if(@Operation='GetStreet_name')\r\n\tbegin \r\n\tselect Street_name from Street with (nolock) where Street_id=@Id\r\n\tend\r\n\telse \r\n\tbegin \r\n\tselect Null;\r\n\tend\r\nEND";
        public string getViolation = "CREATE PROCEDURE [dbo].[getViolation] \r\n AS\r\nBEGIN\r\n SELECT \r\n       [Violation_id]\r\n      ,[Violation_date]\r\n      ,[Plate_id]\r\n      ,vio.[Street_id]\r\n      ,[Teaffic_man_id]\r\n      ,vio.[Violation_type_id]\r\n      ,[Notise]\r\n      ,[Violation_penalty]\r\n      ,[Payment_status]\r\n\t  ,[vehicle_id]\t\r\n\t  ,[VounchrNum]\r\n\t  ,[Provinceid]\r\n\t  ,plattype.Plate_type_name\r\n\t  ,viotype.Violation_type_name\r\n\t  ,trfcman.Traffic_man_name\r\n\t  ,st.Street_name\r\n\t  ,viotype.Maximum_price As Amount\r\n      ,[CreatedOn]\r\n      ,[Createdby]\r\n      ,[UpdateOn]\r\n      ,[UpdatedBy]\r\n      \r\n      \r\n  FROM [dbo].[Violation] vio with(nolock)  \r\n       inner join Violation_type viotype with (nolock)  on vio.Violation_type_id=viotype.Violation_type_id\r\n\t   inner join Plate_type plattype with (nolock) on plattype.Plate_type_id=vio.Plate_id\r\n\t   inner join Street st with (nolock) on st.Street_id=vio.Street_id\r\n\t   inner join Traffic_man trfcman with  (nolock) on trfcman.Traffic_man_id=vio.Teaffic_man_id\r\nEND\r\n";
        public string getviolationFoEdit = "\r\nCREATE PROCEDURE [dbo].[getviolationFoEdit]\r\n@violationId int\r\n\t\r\nAS\r\nBEGIN\r\n\t\r\n\tSET NOCOUNT ON;\r\n\r\n SELECT \r\n       [Violation_id]\r\n      ,[Violation_date]\r\n      ,[Plate_id]\r\n      ,vio.[Street_id]\r\n      ,[Teaffic_man_id]\r\n      ,vio.[Violation_type_id]\r\n      ,[Notise]\r\n      ,[Violation_penalty]\r\n      ,[Payment_status]\r\n\t  ,[vehicle_id]\t\r\n\t  ,[VounchrNum]\r\n\t  ,[Provinceid]\r\n\t  ,plattype.Plate_type_name\r\n\t  ,viotype.Violation_type_name\r\n\t  ,trfcman.Traffic_man_name\r\n\t  ,st.Street_name\r\n\t  ,viotype.Maximum_price As Amount\r\n      ,[CreatedOn]\r\n      ,[Createdby]\r\n      ,[UpdateOn]\r\n      ,[UpdatedBy]\r\n  FROM [dbo].[Violation] vio with(nolock)  \r\n       inner join Violation_type viotype with (nolock)  on vio.Violation_type_id=viotype.Violation_type_id\r\n\t   inner join Plate_type plattype with (nolock) on plattype.Plate_type_id=vio.Plate_id\r\n\t   inner join Street st with (nolock) on st.Street_id=vio.Street_id\r\n\t   inner join Traffic_man trfcman with  (nolock) on trfcman.Traffic_man_id=vio.Teaffic_man_id \r\n\t   where vio.Violation_id=@violationId\r\nEND\r\nGO\r\n";
        public string QueryViolation = "\r\nCREATE PROCEDURE [dbo].[QueryViolation]\r\n@vehicle_id nvarchar(30),\r\n@Provinceid  int,\r\n@Plate_id   int\r\n\r\nAS\r\nBEGIN\r\n SELECT \r\n       [Violation_id]\r\n      ,[Violation_date]\r\n      ,[Plate_id]\r\n      ,vio.[Street_id]\r\n      ,[Teaffic_man_id]\r\n      ,vio.[Violation_type_id]\r\n      ,[Notise]\r\n      ,[Violation_penalty]\r\n      ,[Payment_status]\r\n\t  ,[vehicle_id]\t\r\n\t  ,[VounchrNum]\r\n\t  ,[Provinceid]\r\n\t  ,plattype.Plate_type_name\r\n\t  ,viotype.Violation_type_name\r\n\t  ,trfcman.Traffic_man_name\r\n\t  ,st.Street_name\r\n\t  ,viotype.Maximum_price As Amount\r\n      ,[CreatedOn]\r\n      ,[Createdby]\r\n      ,[UpdateOn]\r\n      ,[UpdatedBy]\r\n      \r\n      \r\n  FROM [dbo].[Violation] vio with(nolock)  \r\n       inner join Violation_type viotype with (nolock)  on vio.Violation_type_id=viotype.Violation_type_id\r\n\t   inner join Plate_type plattype with (nolock) on plattype.Plate_type_id=vio.Plate_id\r\n\t   inner join Street st with (nolock) on st.Street_id=vio.Street_id\r\n\t   inner join Traffic_man trfcman with  (nolock) on trfcman.Traffic_man_id=vio.Teaffic_man_id\r\n\t   inner join Province with (nolock) on Province.Province_id=vio.Provinceid\r\n\t   where \r\n\t   vio.vehicle_id=@vehicle_id  and  vio.Provinceid=@Provinceid and vio.Plate_id=@Plate_id  \r\nEND\r\n";
        public string GetStreetbyName = "CREATE PROCEDURE GetStreetbyName\r\n@name nvarchar(25)\r\nAS\r\nBEGIN\r\n\t\r\n\r\nSELECT [Street_id]\r\n      ,[Street_name]\r\n      ,[Directerate_id]\r\n  FROM [dbo].[Street]\r\n  where Street_id=@name\r\nEND";
        public string GetViolationByName = "CREATE PROCEDURE [dbo].[GetViolationByName] \r\n@nameofViolation nvarchar(25)\r\nAS\r\nBEGIN\r\n\t\r\nSELECT [Violation_type_id]\r\n      ,[Violation_type_name]\r\n      ,[Minimum_price]\r\n      ,[Maximum_price]\r\n      ,[Penalty]\r\n      ,[Interception_status]\r\n  FROM [dbo].[Violation_type]\r\n  where Violation_type_name=@nameofViolation\r\nEND";
        public string GetplatypeByName = "CREATE PROCEDURE GetplatypeByName\r\n\t@nameType nvarchar(25)\r\nAS\r\nBEGIN\r\n\tSET NOCOUNT ON;\r\nSELECT [Plate_type_id]\r\n      ,[Plate_type_name]\r\n      ,[Status]\r\n  FROM [dbo].[Plate_type]\r\n  where [Plate_type_name]=@nameType\r\nEND";
        public string Rep_VilationbyRecipt = "\r\nCREATE PROCEDURE [dbo].[Rep_VilationbyRecipt]\r\n\t@fromData DateTime,\r\n\t@toData DateTime\r\nAS\r\nBEGIN\r\n\t  SELECT \r\n\t    \r\n           RECPT.RECEIPT_ID,\r\n\t\t   VIOL.VEHICLE_ID,\r\n\t\t     RECPT.Receipt_amount,\r\n\t\t   VIOL.PAYMENT_STATUS,\r\n\t\t   RCPTDET.NAMEOFPAID,\r\n\t\t   PLATYPE.PLATE_TYPE_NAME,\r\n\t\t   PROV.PROVINCE_ID,\r\n\t\t   RCPTDET.RESONOFPAID\r\n\t\t   , count(RECPT.RECEIPT_ID) countOfViolation\r\n\t\t\r\n\r\n              FROM VIOLATION VIOL WITH (NOLOCK) \r\n              INNER JOIN RECEIPT_DETAIL RCPTDET WITH(NOLOCK) ON RCPTDET.VIOLATION_ID=VIOL.VIOLATION_ID\r\n\t\t\t  INNER JOIN RECEIPT RECPT WITH(NOLOCK) ON RECPT.RECEIPT_ID=RCPTDET.RECEIPT_ID\r\n\t\t\t  INNER JOIN PLATE_TYPE PLATYPE WITH (NOLOCK) ON PLATYPE.PLATE_TYPE_ID=VIOL.PLATE_ID\r\n\t\t\t  INNER JOIN PROVINCE PROV WITH (NOLOCK) ON PROV.PROVINCE_ID=VIOL.PROVINCEID\r\n\t\t\t  WHERE \r\n\t\t\t  VIOL.PAYMENT_STATUS=1 AND\r\n\t\t\t  CAST(RECPT.RECEIPT_DATE AS DATE)>=cast(@fromData as date)\r\n\t\t\t  and CAST(RECPT.RECEIPT_DATE AS DATE) <= cast(@toData as date)\r\n\t\t\t    group by RECPT.Receipt_id,  VIOL.VEHICLE_ID,RECPT.Receipt_amount, VIOL.PAYMENT_STATUS,RCPTDET.NAMEOFPAID\r\n\t\t\t  , PLATYPE.PLATE_TYPE_NAME, PROV.PROVINCE_ID,   RCPTDET.RESONOFPAID\r\nEND\r\nGO\r\n";
        public string Getreviewviolation = "\r\nCREATE PROCEDURE Getreviewviolation\r\n@vehicleId int,\r\n@violationType nvarchar(10),\r\n@violationprov nvarchar(10),\r\n@DateReview\tDateTime\r\nAS\r\nBEGIN\r\n SELECT top 1 [ID]\r\n      ,[vehicleId]\r\n      ,[violationType]\r\n      ,[violationprov]\r\n      ,cast([DateReview] as date)\r\n      FROM [dbo].[ReviewViolation]\r\n\t   where [vehicleId]=@vehicleId and [violationType]=@violationType and [violationprov]=@violationprov \r\n\t   order by 1desc \r\nEND\r\nGO\r\n";
    }
}
